modules/distribution/pom.xml
modules/distribution/src/assembly/filter.properties
modules/distribution/src/bin/wso2server.bat
modules/distribution/src/bin/wso2server.sh
modules/features/pom.xml
modules/features/product/org.wso2.das.styles.feature/pom.xml
modules/features/product/pom.xml
modules/features/service/org.wso2.das.multitenancy.dashboard.ui.feature/pom.xml
modules/features/service/org.wso2.das.multitenancy.styles.feature/pom.xml
modules/features/service/pom.xml
modules/integration/pom.xml
modules/integration/tests-common/admin-clients/pom.xml
modules/integration/tests-common/integration-test-utils/pom.xml
modules/integration/tests-common/ui-pages/pom.xml
modules/integration/tests-integration/pom.xml
modules/integration/tests-ui-integration/pom.xml
modules/integration/tests-ui-integration/tests-ui/pom.xml
modules/org.wso2.cep.storm.dependencies/pom.xml
modules/org.wso2.das.multitenancy.dashboard.ui/pom.xml
modules/p2-profile-gen/pom.xml
modules/samples/capps/pom.xml
modules/samples/pom.xml
modules/samples/publishers/pom.xml
modules/samples/udfs/country-code-ip/pom.xml
modules/samples/udfs/pom.xml
modules/styles/pom.xml
modules/styles/product/pom.xml
modules/styles/service/pom.xml
pom.xml

Revert "Version upgrades for DAS 3.1.0 Milestone release"

---

modules/distribution/src/repository/conf/domain-template/temperature-analysis.xml
modules/integration/tests-common/admin-clients/src/main/java/org/wso2/das/integration/common/clients/ExecutionManagerAdminServiceClient.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/sparktemplates/SparkTemplateDeployerTestCase.java
modules/integration/tests-integration/src/test/resources/sparktemplates/TestDomain.xml

Please merge this after https://github.com/wso2/carbon-analytics/pull/181 has being merged.

Changes related to Analytics Execution Manager.

---

modules/distribution/src/repository/conf/domain-template/temperature-analysis.xml
modules/integration/tests-common/admin-clients/src/main/java/org/wso2/das/integration/common/clients/ExecutionManagerAdminServiceClient.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/sparktemplates/SparkTemplateDeployerTestCase.java
modules/integration/tests-integration/src/test/resources/sparktemplates/TestDomain.xml

Changing Execution Manager Template as a follow-up to IoT Analytics 1.0 alpha release review.

---

modules/distribution/src/repository/conf/template-manager/domain-template/SensorAnalyticsDomain.xml
modules/distribution/src/repository/conf/template-manager/gadget-templates/numberchart/gadget.xml
modules/distribution/src/repository/conf/template-manager/gadget-templates/numberchart/js/core/gadget-core.js
modules/distribution/src/repository/conf/template-manager/gadget-templates/numberchart/js/core/provider-client.js
modules/distribution/src/repository/conf/template-manager/gadget-templates/numberchart/js/core/realtime-provider-api.js

Corresponding to https://github.com/wso2/product-cep/pull/264

Modifying sample template file in template manager due to tenant issue fixes in dashboard

---

modules/distribution/pom.xml
modules/distribution/src/assembly/bin.xml
modules/distribution/src/bin/wso2cep-samples.bat
modules/distribution/src/bin/wso2cep-samples.sh

CEP samples.zip will be copied in to {das_home}/samples/cep location.
Reference PR: https://github.com/wso2/product-cep/pull/266

Adding CEP Samples to DAS distribution

---

modules/components/org.wso2.carbon.stream.processor.core/src/main/java/org/wso2/carbon/stream/processor/core/internal/StreamProcessorDeployer.java
modules/components/org.wso2.carbon.stream.processor.core/src/main/java/org/wso2/carbon/stream/processor/core/internal/StreamProcessorService.java

Signed-off-by: sajith <sajithshn@gmail.com>

Mandating execution plan name

---

modules/components/org.wso2.carbon.stream.processor.core/src/main/java/org/wso2/carbon/stream/processor/core/internal/StreamProcessorService.java

Signed-off-by: sajith <sajithshn@gmail.com>

Fixing a checkstyle issue

---

modules/samples/artifacts/0009/README.txt
modules/samples/artifacts/0009/store-mongodb-test-plan.siddhi

Added sample Siddhi query for MongoDB Event Table.

Sample Siddhi query for MongoDB Event Table

---

modules/distribution/pom.xml
modules/distribution/src/assembly/bin.xml
modules/samples/artifacts/0012/READMe.txt
modules/samples/artifacts/0012/jms-sample.siddhi
pom.xml

multiple fixes

---

modules/distribution/pom.xml
modules/samples/artifacts/0011/README.txt
modules/samples/artifacts/0011/store-solr-test-plan.siddhi
pom.xml

adding extensions jars

---

modules/samples/artifacts/0013/README
modules/samples/artifacts/0013/UniqueLengthBatchWindowSiddhiAppTest.siddhi

added 0013 sample to the product-das which include sample for Siddhi Execution Unique Extension.
0013 sample folder includes README.text file and UniqueLengthBatchWindowsiddhiApp.siddhi file.

adding 0013 sample - Siddhi Execution Unique Extension

---

modules/distribution/pom.xml
modules/features/pom.xml
modules/features/product/org.wso2.das.styles.feature/pom.xml
modules/features/product/pom.xml
modules/features/service/org.wso2.das.multitenancy.dashboard.ui.feature/pom.xml
modules/features/service/org.wso2.das.multitenancy.styles.feature/pom.xml
modules/features/service/pom.xml
modules/integration/pom.xml
modules/integration/tests-common/admin-clients/pom.xml
modules/integration/tests-common/integration-test-utils/pom.xml
modules/integration/tests-common/ui-pages/pom.xml
modules/integration/tests-integration/pom.xml
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analytics/execution/AnalyticsScriptTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPITenantTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPIUserTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/restservice/analytics/AnalyticsRestTestCase.java
modules/integration/tests-ui-integration/pom.xml
modules/integration/tests-ui-integration/tests-ui/pom.xml
modules/org.wso2.das.multitenancy.dashboard.ui/pom.xml
modules/p2-profile-gen/pom.xml
modules/samples/capps/pom.xml
modules/samples/pom.xml
modules/samples/publishers/pom.xml
modules/samples/udfs/country-code-ip/pom.xml
modules/samples/udfs/pom.xml
modules/styles/pom.xml
modules/styles/product/pom.xml
modules/styles/service/pom.xml
pom.xml

Make DAS 3.1.0-update1 buildable.
Fixes #271

Make DAS 3.1.0-update1 buildable

---

modules/distribution/src/repository/conf/log4j.properties
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analytics/execution/AnalyticsScriptTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPITenantTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPIUserTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/restservice/analytics/AnalyticsRestTestCase.java
modules/p2-profile-gen/pom.xml
pom.xml

Version bumps and general fixes for prepping update 2 release
**NOTE: Should be merged only after carbon-ml 1.2.5 is released.**

Version bumps for update 2 release

---

modules/distribution/src/repository/conf/log4j.properties
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analytics/execution/AnalyticsScriptTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPITenantTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPIUserTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/restservice/analytics/AnalyticsRestTestCase.java
modules/p2-profile-gen/pom.xml
pom.xml

Revert "Version bumps for update 2 release"

---

modules/distribution/src/repository/conf/log4j.properties
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analytics/execution/AnalyticsScriptTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPITenantTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/analyticsapi/AnalyticsAPIUserTestCase.java
modules/integration/tests-integration/src/test/java/org/wso2/das/integration/tests/restservice/analytics/AnalyticsRestTestCase.java
modules/p2-profile-gen/pom.xml
pom.xml

Revert "Revert "Version bumps for update 2 release""

---

modules/distribution/pom.xml
modules/distribution/src/assembly/bin.xml
modules/distribution/src/scripts/forget-me.bat
modules/distribution/src/scripts/forget-me.sh
modules/distribution/src/scripts/overrides/forget-me
modules/distribution/src/scripts/overrides/forget-me.bat
pom.xml

This PR adds the forget-me tool to DAS.
Also, this includes a version bump of carbon-analytics-common

Add forget-me tool

---

pom.xml

$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? **yes**
- Ran FindSecurityBugs plugin and verified report? **yes**
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? **yes**

Bump carbon-ml version to v1.2.8

---

modules/distribution/src/scripts/forget-me.bat
modules/distribution/src/scripts/overrides/forget-me.bat

> Making use of DAL jars for forget-me tool
> N/A
>  Forget-me tool needs DAL jar for performing persisted stream animalization. Adding those libs to the classpath for tool to work
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> Windows 10, JDK 1.8_131
> N/A

Fix for forget-me.bat

---

pom.xml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Upgrading carbon-analytics dependency version.

---

modules/distribution/src/privacy-policies/pages/cookie-policy.jag
modules/distribution/src/privacy-policies/pages/privacy-policy.jag

$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? **yes**
- Ran FindSecurityBugs plugin and verified report? **yes**
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? **yes**

Add cookie policy and privacy policy

---

modules/distribution/src/privacy-policies/pages/cookie-policy.jag

$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? **yes**
- Ran FindSecurityBugs plugin and verified report? **yes**
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? **yes**

Fix cookies table in the cookie policy table

---

modules/styles/product/src/main/resources/META-INF/product.xml
pom.xml

> Bump dependency versions
> Fix for [wso2/product-das#303](https://github.com/wso2/product-das/issues/303)

Bump dependency versions
